#!/usr/bin/env php
<?php
error_reporting(E_ALL);
ini_set('display_errors', 'on');
ini_set('limit_memory','512M');
date_default_timezone_set('Asia/Shanghai');

define("__APP__",__DIR__);

define("__ROOT__",dirname(__DIR__));

define("__CONF__",__DIR__. '/conf.d');


require (__DIR__ .'/vendor/autoload.php');
$setting = array(
	'root' => __DIR__,
	);
$app = new \Ypf\Swoole($setting);

//config
$config = new \Ypf\Lib\Config();
$config->load(__CONF__);

$app->setServerConfigIni(__CONF__ . '/server.conf');

//request
$app->set('request', new \Ypf\Http\Request());

//response
$response =new \Ypf\Http\Response(); 
$app->set('response', $response);

//view
$view = new \Cat\View(); 
$view->setTemplateDir(__APP__ . '/CatView/');
$app->set('view', $view);

$app->set('config', $config);

$app->addBeforeAction("Cat\Common\Router\index");

$app->start();


