#!/usr/bin/env php
<?php
error_reporting(E_ALL);
ini_set('display_errors', 'on');
ini_set('limit_memory','512M');
date_default_timezone_set('Asia/Shanghai');

define("__APP__",__DIR__);

define("__ROOT__",dirname(__DIR__));

define("__CONF__",__DIR__. '/conf.d');


require (__DIR__ .'/vendor/autoload.php');

use Psr\Log\LoggerInterface;

$services   = include __DIR__.'/services.php';

$app = new \Ypf\Swoole($services);

$app->setServerConfigIni(__CONF__ . '/server.conf');

$view = new \Cat\View(); 
$view->setTemplateDir(__APP__ . '/CatView/');
$app->set('view', $view);

$app->addBeforeAction("Cat\Common\Router\index");

$app->start();

//config
//$config = new \Ypf\Lib\Config();
//$config->load(__CONF__);

//$app->set('config', $config);



//$app->logger->debug('This will be logged to the file');
//$app->logger->error('This will be logged to the mail');



